---
galaxy_info:
  author: Chad Elliott
  description: Enable and validate the OpenShift integrated image registry.
  company: Automation Development Office
  license: GPL-3.0-or-later
  min_ansible_version: "2.16.0"
  galaxy_tags: []

dependencies: []
