---
# yamllint disable rule:line-length
capsule_install_rhn_repos:
  - "rhel-9-for-x86_64-baseos-rpms"
  - "rhel-9-for-x86_64-appstream-rpms"
  - >-
    satellite-capsule-{{ capsule_install_deployment_version }}-for-rhel-9-x86_64-rpms
  - >-
    satellite-maintenance-{{ capsule_install_deployment_version }}-for-rhel-9-x86_64-rpms
# yamllint enable rule:line-length
# Capsule install requirements
capsule_install_os_version: "9"
capsule_install_min_cpu_count: 4
# Size in MB
capsule_install_min_memory_size: 12288
# Size in GB
capsule_install_data_disk_min_size: 500
capsule_install_min_pulp_size: 300
capsule_install_min_pgsql_size: 20
capsule_install_pre_check: false
# Storage
capsule_install_pulp_size: 1500g
capsule_install_pgsql_size: 150g
capsule_install_data_device: /dev
capsule_install_vg_name: "capsule"
capsule_install_req_dirs:
  - mount_point: /var/lib/pulp
    lv_name: pulp
    lv_size: "{{ capsule_install_pulp_size }}"
  - mount_point: /var/lib/pgsql
    lv_name: pgsql
    lv_size: "{{ capsule_install_pgsql_size }}"

# Packages
capsule_install_packages:
  - satellite-capsule
  - chrony
  - sos
  - fapolicyd 
  - vim 
  - bash-completion 
  - bind-utils

capsule_install_scenario: "capsule"
capsule_install_deployment_version: "6.19"
capsule_install_selinux_state: "enforcing"

# Administration
capsule_install_admin_username: "admin"
capsule_install_timezone: "UTC"
capsule_install_location: ""
capsule_install_setup_insights: false

capsule_install_org_id:
capsule_install_activation_key:
capsule_install_satellite_fqdn:
capsule_install_certs: []
capsule_install_sync_wait_time: 86400
capsule_install_lifecycle_environments: []

# Load Balancing
capsule_install_satellite_haproxy: false
capsule_install_loadbalancer_fqdn: ""
capsule_install_loadbalancer_activation_key: ""
capsule_install_satellite_loadbalancer_ports:
  - 80/tcp
  - 443/tcp
  - 8000/tcp
  - 9090/tcp

# Install
capsule_install_installer_options:
  - '--foreman-proxy-register-in-foreman true'
  - '--foreman-proxy-foreman-base-url https://{{ capsule_install_satellite_fqdn }}'
  - '--foreman-proxy-trusted-hosts {{ capsule_install_satellite_fqdn }}'
  - '--foreman-proxy-trusted-hosts {{ ansible_fqdn }}'
  - '--foreman-proxy-oauth-consumer-key {{ capsule_install_foreman_proxy_oauth_consumer_key }}'
  - '--foreman-proxy-oauth-consumer-secret {{ capsule_install_foreman_proxy_oauth_consumer_secret }}'
  - '--foreman-proxy-plugin-remote-execution-script-mode=ssh'
  - '--certs-tar-file /root/capsule_cert/{{ ansible_fqdn }}/{{ ansible_fqdn }}-capsule-certs.tar'
  - '--enable-foreman-proxy-plugin-remote-execution-script'
  - '--foreman-proxy-content-enable-docker=false'

capsule_install_loadbalanced_options:
  - '--foreman-proxy-register-in-foreman true'
  - '--foreman-proxy-foreman-base-url https://{{ capsule_install_satellite_fqdn }}'
  - '--foreman-proxy-trusted-hosts {{ capsule_install_satellite_fqdn }}'
  - '--foreman-proxy-trusted-hosts {{ ansible_fqdn }}'
  - '--foreman-proxy-oauth-consumer-key {{ capsule_install_foreman_proxy_oauth_consumer_key }}'
  - '--foreman-proxy-oauth-consumer-secret {{ capsule_install_foreman_proxy_oauth_consumer_secret }}'
  - '--foreman-proxy-plugin-remote-execution-script-mode=ssh'
  - '--certs-tar-file /root/capsule_cert/{{ ansible_fqdn }}/{{ ansible_fqdn }}-capsule-certs.tar'
  - '--enable-foreman-proxy-plugin-remote-execution-script'
  - '--foreman-proxy-content-enable-docker=false'
  - '--certs-cname {{ capsule_install_loadbalancer_fqdn }}'
  - '--foreman-proxy-registration-url https://{{ capsule_install_loadbalancer_fqdn }}:9090'
  - '--foreman-proxy-template-url http://{{ capsule_install_loadbalancer_fqdn }}:8000'

...