---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offline-fixture
spec:
  selector:
    matchLabels:
      app: offline-fixture
  template:
    metadata:
      labels:
        app: offline-fixture
    spec:
      containers:
        - name: pega
          image: {{ .Values.image | quote }}
