---
# tasks file for infra.ado.capsule_install

- name: Preliminary Check
  ansible.builtin.include_tasks: preliminary_check.yml

- name: Block tasks to run when pre_check is set to false
  when: not (capsule_install_pre_check | bool)
  block:
    - name: RHSM Subscribe
      ansible.builtin.include_tasks: rhsm_subscribe.yml

    - name: Patch
      ansible.builtin.include_role:
        name: infra.ado.satellite_install
        tasks_from: patch
      vars:
        satellite_install_selinux_state: "{{ capsule_install_selinux_state }}"

    - name: Storage Config
      ansible.builtin.include_role:
        name: infra.ado.satellite_install
        tasks_from: storage_config
      vars:
        satellite_install_vg_name: "{{ capsule_install_vg_name }}"
        satellite_install_data_disk_min_size: "{{ capsule_install_data_disk_min_size }}"
        satellite_install_data_device: "{{ capsule_install_data_device }}"
        satellite_install_data_device_name: "{{ capsule_install_data_device_name }}"
        satellite_install_req_dirs: "{{ capsule_install_req_dirs }}"
        satellite_install_data_disk: "{{ capsule_install_data_disk }}"

    - name: Install Packages
      ansible.builtin.include_tasks: install_packages.yml

    - name: Configure Firewall
      ansible.builtin.include_tasks: configure_firewall.yml

    - name: Configure DNS
      ansible.builtin.include_tasks: dns_config.yml

    - name: Generate Custom Capsule Certificate
      ansible.builtin.include_tasks: generate_cap_custom_cert.yml

    - name: Install Capsule
      ansible.builtin.include_tasks: install_capsule.yml

    - name: Post Config
      ansible.builtin.include_tasks: post_config.yml

    - name: Sync Capsule
      ansible.builtin.include_tasks: sync_capsule.yml

    - name: HAProxy
      ansible.builtin.include_tasks: haproxy.yml
      when: capsule_install_satellite_haproxy | bool
