---
dependency:
  name: shell
  command: echo Local fixtures only
driver:
  name: default
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
  env:
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - verify
