---
# yamllint disable rule:line-length
dependency:
  name: shell
  command: >-
    ansible-galaxy collection install
    ${MOLECULE_PROJECT_DIRECTORY}/../..
    --force --no-deps
    -p ${HOME}/.ansible/collections

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: >-
      ${HOME}/.ansible/collections:${ANSIBLE_COLLECTIONS_PATH}
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../../roles
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

scenario:
  name: integration_ocp_absent_cleanup
  test_sequence:
    - dependency
    - syntax
    - converge
    - verify
